### ISSUE TITLE
Migrate this library to MavenCentral from JCenter

### ISSUE THREAD

**Issue by AlanChiou** [rakutentech/android-manifest-config#8]
JCenter is deprecated now.
Please migrate this library to MavenCentral from JCenter
https://developer.android.com/studio/build/jcenter-migration

**Comment by corycaywood** [comment]
Thanks for bringing this up @AlanChiou.

We are aware that JCenter will be shutdown in February 2022, so we are currently moving our libraries to Maven Central. Currently we are setting up the publishing config for this repo, so it will be migrated soon.

I will update the ticket when this is complete.

**Comment by corycaywood** [comment]
We've finished migrating this library to Maven Central. Note that we changed the Group ID to `io.github.rakutentech.manifestconfig`. So you will need to update your dependency declarations as follows:

```
repositories {
  mavenCentral()
}
dependencies {
  implementation        "io.github.rakutentech.manifestconfig:manifest-config-annotations:0.2.0"
  annotationProcessor   "io.github.rakutentech.manifestconfig:manifest-config-processor:0.2.0"
}
```
